<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="btheado.20191228091430.1"><vh>leo pytests</vh>
<v t="btheado.20191227180740.1"><vh>@file conftest.py</vh></v>
<v t="btheado.20191203182713.1"><vh>@file leoNodes_test.py</vh></v>
<v t="btheado.20191216205716.1"><vh>@file dirty_save_test.py</vh></v>
<v t="btheado.20191224142353.1"><vh>@file external_file_changes_test.py</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="btheado.20191228091430.1">@language python
</t>
</tnodes>
</leo_file>
